### ISSUE TITLE
alerting when alerts are off, packet loss always zero

### ISSUE THREAD

**Issue by ScottBessel** [pricemi115/homebridge-grumptech-netnanny#66]
I just installed version 1.6.1 of this plugin on a raspberry PI.
I am not sure where to put this issue, but since this was where I was directed, here it is.

OS	Raspbian GNU/Linux Bullseye (11)
Homebridge version: v1.7.0 
UI version: v4.56.4 

No matter what I do the packet loss always shows zero.  If I set the alert to packet loss I get a lot of random alerts, all I want is to be alerted if it is actually down, hence the high loss_limit number, I tried this on a variety of numbers, they seemed to be ignored. I am not sure what is tripping the alerts, as when I get the packet loss alerts there is no packet loss and the connection is still good.
If I turn the alerts all off, as it is set now in the config, I still get alerts for latency, even though the latency is BELOW the setting I have of 200.

On a side note:  you labels in the UI are not the same as the config file, as such the documentation does not correctly relate, so the loss_limit is a confusing setting.

Feature:  It would be nice if I could pick the device type, I.E. light, switch, motion sensor.  The carbon dioxide detector has a particular nasty alert and does not offer as many automation options as the others.
The carbon dioxide alerts don't allow narrowing of the device, just the room, as they are all in the same room the alerts are pretty much meaningless until you drill down to the actual device.
A light switch that I can label "Google Packet Loss" turning on would be simple to see and trigger on.

here is the config:
{
    "settings": {
        "history_logging": {
            "reporting_period": 10,
            "maximum_history_size": 250000,
            "retention_period": 30
        },
        "ping_targets": [
            {
                "target_type": "ipv4",
                "modem_type": "other",
                "target_dest": "8.8.8.8",
                "loss_limit": 90,
                "expected_latency": 200,
                "expected_jitter": 20,
                "peak_expiration": 12,
                "data_filter_time_window": 180,
                "sensor_alert_mask": 0
            },
            {
                "target_type": "uri",
                "modem_type": "other",
                "target_dest": "google-public-dns-b.google.com",
                "loss_limit": 90,
                "expected_latency": 200,
                "expected_jitter": 20,
                "peak_expiration": 12,
                "data_filter_time_window": 180,
                "sensor_alert_mask": 0
            }
        ],
        "ping_period": 20,
        "ping_interval": 1,
        "ping_count": 5,
        "packet_size": 56,
        "enable_history_logging": true
    },
    "_bridge": {
        "username": "0E:65:DF:EB:86:E8",
        "port": 33497
    },
    "platform": "GrumpTechHomebridgeNetNanny"
}

**Comment by pricemi115** [comment]
Hi @ScottBessel 
Thank you for the report. I am guessing that the packet loss issue is a similar issue as #61. I can look into that and have a look.

The names of the 3 accessories under the single device has always been a challenge. It seems that homebridge does not percolate these names very well. But it has been a while since I looked into it, so I can look to see if there are any improvements there. 

When I created this plugin, my thought process was to use the CO sensor as that reports "bad stuff" and the when ping results get large, that is also bad. But I like the idea of using other accessory types and sensors, like motion sensors, which would support automation.

Out of curiosity, what kind of automation would you want to do is the results got into the bad zone?

**Comment by pricemi115** [comment]
Oh. Funny story about the nasty alert from the CO2 sensor...when I was creating this, I was doing the work on my actual home (had not yet thought to create a dev home). During the initial development, I blew up my daughter's phone with CO2 alerts while she was in class. Oops 😅

**Comment by ScottBessel** [comment]
Right now I am installing at a remote location, and need the logging, but I can see an automation where the packet loss shows the internet as down I change one of my lighting strips to red, and back to not-red once back up.
The issue is the alerts are cumbersome and I can't disable for the remote users, and getting CO2 alerts are annoying and the first time is scary.

**Comment by ScottBessel** [comment]
Since you are looking, a feature I would really like to see is the ability to download one of the log files.
I am remote to my install and my only access is the web side, while it has a terminal option and i can see the files it has no way to download a file, the only way I have found is using the homebridge GUI and download a backup file, which contains everything, but it will always be yesterday's data.

**Comment by pricemi115** [comment]
Homebridge and HomeKit are fairly limited in what they can do. But to access the log files, you may want to look into Tailscale with Taildrive shares. That may be the quickest way to get access to the files.

In case you are not familiar with Tailscale:
- https://pimylifeup.com/raspberry-pi-tailscale/
- https://tailscale.com/kb/1369/taildrive
- https://tailscale.com/kb

**Comment by ScottBessel** [comment]
Sorry, my only access to my remote HB install is over the HB web UI, and whatever it has to offer.
I was hoping you might give an option like it does.
![Screenshot 2024-09-22 at 7 06 27 PM](https://github.com/user-attachments/assets/c1a45c36-b483-45e0-a9a8-90f8e2cabfea)
This is my only way to retrieve files. it would also be helpful as then I would have to decipher the log naming convention.

**Comment by pricemi115** [comment]
Sorry for the long delay in processing this report. I was bogged down with other tasks.

Regarding the report of packet loss being 0 all the time..
Unable to reproduce.

Installed v1.6.1 on a fresh install of RasPi
OS: Bookworm (12)
NodeJs: v20.18.0
Homebridge: v1.8.5
HomebridgeUI: v4.62.0

- Created a network target for Google DNS (IPV4 8.8.8.8).
- Verified normal behavior for all 3 C02 Sensors (Latency, Jitter, Packet Loss).
- Configured router to block internet access for the RasPi device.
- Packet Loss seen to be 100% and alert was issued.
   ** Observed odd behavior where Jitter was locked on last reported value, whereas Latency was 0 ms
- Re-configured router to permit internet access.
- Values returned to normal and the Alert for Packet Loss Cleared.
- Repeated with the Alarm Mode set to Latency and Jitter only. Same behavior as above but there were no alerts.

It is likely that the observed problem was due to ping errors related to spawning the ping request. 
Recommend enabling debug logs in the Homebridge configuration.
- Under 'Startup & Environment`
-- enable `Homebridge Debug Mode -D`
-- In the `DEBUG` environment variable field enter: network_target

If the problem persists, enable logging and provide the logs in this issue.

-----------
Regarding the issues with automation. It is true that HomeKit automation only allows an automation to happen when one of the sensors detects CO2. When the sensor no longer detects CO2 is not a trigger that the user can select for an automation. Motion sensors on the other hand, do allow the user to set a trigger for detecting motion and no longer detecting motion. Allowing a motion sensor in addition or instead of the CO2 alarm should resolve the automation request noted previously.
This will be handled under a separate feature request.

------------
Remote access to the backup logs is beyond the scope of a Homebridge plugin. 
The log files are simple CSV text files that are named according to the following format `History_<timestamp>.csv`, where the timestamp is the number of milliseconds since the Unix Epoch. So more recent files will have larger numbers in the timestamp. The files are located in the Homebridge Storage Path. For example on Linux/RasPi - the files are in /var/lib/homebridge/GrumpTechHomebridgeNetNanny/
